### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lupoglaz** [NinelK/WavesProject#1]
1. Scripts to generate dataset
2. Make distribution of centers uniform in the dataset (uniTraining)
3. Take uniform random subset from uniTraining as validation/training split

**Comment by NinelK** [comment]
1. Scripts that generate datasets from the raw simulated data were added (processing/)
2. Distribution turns out to be almost uniform: all centers lay within a circle with the radius of ~30 px, but within this circle, the distribution is almost uniform. There were only ~370 unique simulations, so it might be that non-uniformity comes solely from the small size of the dataset. Therefore, I will run more simulations in the background to get more unique spirals.
3. Done (/processing/data_split.py)
